// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: realionetwork/stable/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPackageRequest is request type for the Query/Package RPC method.
type QueryPackageRequest struct {
	// connection_id is the connection identifier.
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// nonce is the package nonce.
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *QueryPackageRequest) Reset()         { *m = QueryPackageRequest{} }
func (m *QueryPackageRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPackageRequest) ProtoMessage()    {}
func (*QueryPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84125a8dd31ea90e, []int{0}
}
func (m *QueryPackageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPackageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPackageRequest.Merge(m, src)
}
func (m *QueryPackageRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPackageRequest proto.InternalMessageInfo

func (m *QueryPackageRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *QueryPackageRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

// QueryPackageResponse is response type for the Query/Package RPC method.
type QueryPackageResponse struct {
	// package is the tracked package.
	Package TrackedPackage `protobuf:"bytes,1,opt,name=package,proto3" json:"package"`
}

func (m *QueryPackageResponse) Reset()         { *m = QueryPackageResponse{} }
func (m *QueryPackageResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPackageResponse) ProtoMessage()    {}
func (*QueryPackageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84125a8dd31ea90e, []int{1}
}
func (m *QueryPackageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPackageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPackageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPackageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPackageResponse.Merge(m, src)
}
func (m *QueryPackageResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPackageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPackageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPackageResponse proto.InternalMessageInfo

func (m *QueryPackageResponse) GetPackage() TrackedPackage {
	if m != nil {
		return m.Package
	}
	return TrackedPackage{}
}

// QueryPendingPackagesRequest is request type for the Query/PendingPackages RPC
// method.
type QueryPendingPackagesRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPendingPackagesRequest) Reset()         { *m = QueryPendingPackagesRequest{} }
func (m *QueryPendingPackagesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingPackagesRequest) ProtoMessage()    {}
func (*QueryPendingPackagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84125a8dd31ea90e, []int{2}
}
func (m *QueryPendingPackagesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingPackagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingPackagesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingPackagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingPackagesRequest.Merge(m, src)
}
func (m *QueryPendingPackagesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingPackagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingPackagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingPackagesRequest proto.InternalMessageInfo

func (m *QueryPendingPackagesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryPendingPackagesResponse is response type for the Query/PendingPackages
// RPC method.
type QueryPendingPackagesResponse struct {
	// packages are the current pending packages.
	Packages []TrackedPackage `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPendingPackagesResponse) Reset()         { *m = QueryPendingPackagesResponse{} }
func (m *QueryPendingPackagesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingPackagesResponse) ProtoMessage()    {}
func (*QueryPendingPackagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84125a8dd31ea90e, []int{3}
}
func (m *QueryPendingPackagesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingPackagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingPackagesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingPackagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingPackagesResponse.Merge(m, src)
}
func (m *QueryPendingPackagesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingPackagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingPackagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingPackagesResponse proto.InternalMessageInfo

func (m *QueryPendingPackagesResponse) GetPackages() []TrackedPackage {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *QueryPendingPackagesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryPackageRequest)(nil), "realionetwork.stable.v1.QueryPackageRequest")
	proto.RegisterType((*QueryPackageResponse)(nil), "realionetwork.stable.v1.QueryPackageResponse")
	proto.RegisterType((*QueryPendingPackagesRequest)(nil), "realionetwork.stable.v1.QueryPendingPackagesRequest")
	proto.RegisterType((*QueryPendingPackagesResponse)(nil), "realionetwork.stable.v1.QueryPendingPackagesResponse")
}

func init() {
	proto.RegisterFile("realionetwork/stable/v1/query.proto", fileDescriptor_84125a8dd31ea90e)
}

var fileDescriptor_84125a8dd31ea90e = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xb1, 0xb5, 0x3a, 0x2a, 0xc2, 0x18, 0x30, 0xc4, 0xb2, 0xc6, 0x8d, 0x68, 0x15,
	0x33, 0x43, 0xaa, 0x82, 0xe2, 0xc9, 0x1e, 0x2c, 0xbd, 0xc5, 0xc5, 0x93, 0x97, 0x32, 0xbb, 0x79,
	0x6c, 0x97, 0x24, 0xf3, 0xb6, 0x3b, 0x93, 0x68, 0x29, 0xbd, 0xf8, 0x09, 0x04, 0x3f, 0x85, 0x57,
	0x3f, 0x45, 0x8f, 0x05, 0x2f, 0x9e, 0x54, 0x12, 0x3f, 0x88, 0xec, 0xce, 0xc4, 0x34, 0x92, 0x90,
	0xe6, 0x36, 0x99, 0xbc, 0xf7, 0x7f, 0xbf, 0xff, 0x7f, 0xde, 0xd2, 0x46, 0x06, 0xb2, 0x97, 0xa0,
	0x02, 0xf3, 0x01, 0xb3, 0xae, 0xd0, 0x46, 0x86, 0x3d, 0x10, 0xc3, 0x96, 0x38, 0x1c, 0x40, 0x76,
	0xc4, 0xd3, 0x0c, 0x0d, 0xb2, 0xdb, 0x33, 0x45, 0xdc, 0x16, 0xf1, 0x61, 0xab, 0xf6, 0x38, 0x42,
	0xdd, 0x47, 0x2d, 0x42, 0xa9, 0xc1, 0x76, 0x88, 0x61, 0x2b, 0x04, 0x23, 0x5b, 0x22, 0x95, 0x71,
	0xa2, 0xa4, 0x49, 0x50, 0x59, 0x91, 0x5a, 0x25, 0xc6, 0x18, 0x8b, 0xa3, 0xc8, 0x4f, 0xee, 0x76,
	0x33, 0x46, 0x8c, 0x7b, 0x20, 0x64, 0x9a, 0x08, 0xa9, 0x14, 0x9a, 0xa2, 0x45, 0xbb, 0x7f, 0xef,
	0x2f, 0xa2, 0x73, 0x08, 0x45, 0x95, 0xdf, 0xa6, 0xb7, 0xde, 0xe6, 0xb3, 0xdb, 0x32, 0xea, 0xca,
	0x18, 0x02, 0x38, 0x1c, 0x80, 0x36, 0xac, 0x41, 0x6f, 0x44, 0xa8, 0x14, 0x44, 0xb9, 0xe2, 0x7e,
	0xd2, 0xa9, 0x92, 0x3a, 0xd9, 0xba, 0x1a, 0x5c, 0x9f, 0x5e, 0xee, 0x75, 0x58, 0x85, 0xae, 0x2b,
	0x54, 0x11, 0x54, 0xcb, 0x75, 0xb2, 0xb5, 0x16, 0xd8, 0x1f, 0xfe, 0x3e, 0xad, 0xcc, 0x2a, 0xea,
	0x14, 0x95, 0x06, 0xb6, 0x4b, 0x37, 0x52, 0x7b, 0x55, 0x88, 0x5d, 0xdb, 0x7e, 0xc8, 0x17, 0x44,
	0xc3, 0xdf, 0x65, 0x32, 0xea, 0x42, 0xc7, 0x29, 0xec, 0xac, 0x9d, 0xfe, 0xbc, 0x5b, 0x0a, 0x26,
	0xdd, 0x3e, 0xd0, 0x3b, 0x76, 0x00, 0xa8, 0x4e, 0xa2, 0x62, 0x57, 0xa5, 0x27, 0xe8, 0x6f, 0x28,
	0x9d, 0xe6, 0xe7, 0x46, 0x3d, 0xe0, 0x36, 0x6c, 0x9e, 0x87, 0xcd, 0xed, 0xf3, 0xb8, 0xb0, 0x79,
	0x7b, 0x6a, 0x3b, 0x38, 0xd7, 0xe9, 0x7f, 0x23, 0x74, 0x73, 0xfe, 0x1c, 0x67, 0x68, 0x8f, 0x5e,
	0x71, 0x48, 0xba, 0x4a, 0xea, 0x97, 0x56, 0x77, 0xf4, 0xaf, 0x9d, 0xed, 0xce, 0x30, 0x97, 0x5d,
	0x3c, 0xcb, 0x98, 0x2d, 0xc7, 0x79, 0xe8, 0xed, 0x5f, 0x65, 0xba, 0x5e, 0x40, 0xb3, 0xaf, 0x84,
	0x6e, 0xb8, 0x71, 0xec, 0xc9, 0x42, 0xae, 0x39, 0x6f, 0x5f, 0x6b, 0x5e, 0xb0, 0xda, 0x8e, 0xf7,
	0x5f, 0x7f, 0xfa, 0xfe, 0xe7, 0x4b, 0xf9, 0x15, 0x7b, 0x29, 0x16, 0x2d, 0xdc, 0xc4, 0xa6, 0x38,
	0x9e, 0xd9, 0xa9, 0x13, 0x71, 0x5c, 0x6c, 0xcc, 0x49, 0xce, 0x7a, 0xf3, 0xbf, 0x94, 0xd9, 0xb3,
	0x25, 0x14, 0x73, 0x1f, 0xbf, 0xf6, 0x7c, 0xc5, 0x2e, 0xe7, 0xe1, 0x51, 0xe1, 0xa1, 0xc1, 0xee,
	0x2d, 0xf5, 0xb0, 0x13, 0x9c, 0x8e, 0x3c, 0x72, 0x36, 0xf2, 0xc8, 0xef, 0x91, 0x47, 0x3e, 0x8f,
	0xbd, 0xd2, 0xd9, 0xd8, 0x2b, 0xfd, 0x18, 0x7b, 0xa5, 0xf7, 0x2f, 0xe2, 0xc4, 0x1c, 0x0c, 0x42,
	0x1e, 0x61, 0xdf, 0xc9, 0x18, 0x88, 0x0e, 0xdc, 0xb1, 0x39, 0x91, 0xfc, 0xe8, 0x44, 0x9b, 0x99,
	0xec, 0xa7, 0xc2, 0x1c, 0xa5, 0xa0, 0xc3, 0xcb, 0xc5, 0xb7, 0xf8, 0xf4, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0x05, 0xf8, 0x7c, 0x51, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Package queries a pending package by nonce and connection ID.
	Package(ctx context.Context, in *QueryPackageRequest, opts ...grpc.CallOption) (*QueryPackageResponse, error)
	// PendingPackages queries all current pending packages.
	PendingPackages(ctx context.Context, in *QueryPendingPackagesRequest, opts ...grpc.CallOption) (*QueryPendingPackagesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Package(ctx context.Context, in *QueryPackageRequest, opts ...grpc.CallOption) (*QueryPackageResponse, error) {
	out := new(QueryPackageResponse)
	err := c.cc.Invoke(ctx, "/realionetwork.stable.v1.Query/Package", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingPackages(ctx context.Context, in *QueryPendingPackagesRequest, opts ...grpc.CallOption) (*QueryPendingPackagesResponse, error) {
	out := new(QueryPendingPackagesResponse)
	err := c.cc.Invoke(ctx, "/realionetwork.stable.v1.Query/PendingPackages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Package queries a pending package by nonce and connection ID.
	Package(context.Context, *QueryPackageRequest) (*QueryPackageResponse, error)
	// PendingPackages queries all current pending packages.
	PendingPackages(context.Context, *QueryPendingPackagesRequest) (*QueryPendingPackagesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Package(ctx context.Context, req *QueryPackageRequest) (*QueryPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Package not implemented")
}
func (*UnimplementedQueryServer) PendingPackages(ctx context.Context, req *QueryPendingPackagesRequest) (*QueryPendingPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingPackages not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Package_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Package(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/realionetwork.stable.v1.Query/Package",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Package(ctx, req.(*QueryPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/realionetwork.stable.v1.Query/PendingPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingPackages(ctx, req.(*QueryPendingPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "realionetwork.stable.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Package",
			Handler:    _Query_Package_Handler,
		},
		{
			MethodName: "PendingPackages",
			Handler:    _Query_PendingPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "realionetwork/stable/v1/query.proto",
}

func (m *QueryPackageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPackageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPackageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPackageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPackageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPackageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Package.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryPendingPackagesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingPackagesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingPackagesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingPackagesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingPackagesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingPackagesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Packages) > 0 {
		for iNdEx := len(m.Packages) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Packages[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPackageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovQuery(uint64(m.Nonce))
	}
	return n
}

func (m *QueryPackageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Package.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryPendingPackagesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPendingPackagesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Packages) > 0 {
		for _, e := range m.Packages {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPackageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPackageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPackageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPackageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPackageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPackageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Package", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Package.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingPackagesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingPackagesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingPackagesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingPackagesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingPackagesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingPackagesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Packages = append(m.Packages, TrackedPackage{})
			if err := m.Packages[len(m.Packages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
