// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: realionetwork/stable/v1/stable.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PackageStatus represents the lifecycle state of a stable-ramp package.
type PackageStatus int32

const (
	// PACKAGE_STATUS_UNSPECIFIED defines an unknown package status.
	PackageStatus_PACKAGE_STATUS_UNSPECIFIED PackageStatus = 0
	// PACKAGE_STATUS_PENDING defines a package that is pending processing.
	PackageStatus_PACKAGE_STATUS_PENDING PackageStatus = 1
	// PACKAGE_STATUS_COMPLETED defines a package that has completed processing.
	PackageStatus_PACKAGE_STATUS_COMPLETED PackageStatus = 2
	// PACKAGE_STATUS_FAILED defines a package that failed processing.
	PackageStatus_PACKAGE_STATUS_FAILED PackageStatus = 3
)

var PackageStatus_name = map[int32]string{
	0: "PACKAGE_STATUS_UNSPECIFIED",
	1: "PACKAGE_STATUS_PENDING",
	2: "PACKAGE_STATUS_COMPLETED",
	3: "PACKAGE_STATUS_FAILED",
}

var PackageStatus_value = map[string]int32{
	"PACKAGE_STATUS_UNSPECIFIED": 0,
	"PACKAGE_STATUS_PENDING":     1,
	"PACKAGE_STATUS_COMPLETED":   2,
	"PACKAGE_STATUS_FAILED":      3,
}

func (x PackageStatus) String() string {
	return proto.EnumName(PackageStatus_name, int32(x))
}

func (PackageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{0}
}

// PackageAction represents whether a package is for deposit or withdrawal.
type PackageAction int32

const (
	// PACKAGE_ACTION_UNSPECIFIED defines an unknown package action.
	PackageAction_PACKAGE_ACTION_UNSPECIFIED PackageAction = 0
	// PACKAGE_ACTION_DEPOSIT defines a deposit package action.
	PackageAction_PACKAGE_ACTION_DEPOSIT PackageAction = 1
	// PACKAGE_ACTION_WITHDRAW defines a withdrawal package action.
	PackageAction_PACKAGE_ACTION_WITHDRAW PackageAction = 2
)

var PackageAction_name = map[int32]string{
	0: "PACKAGE_ACTION_UNSPECIFIED",
	1: "PACKAGE_ACTION_DEPOSIT",
	2: "PACKAGE_ACTION_WITHDRAW",
}

var PackageAction_value = map[string]int32{
	"PACKAGE_ACTION_UNSPECIFIED": 0,
	"PACKAGE_ACTION_DEPOSIT":     1,
	"PACKAGE_ACTION_WITHDRAW":    2,
}

func (x PackageAction) String() string {
	return proto.EnumName(PackageAction_name, int32(x))
}

func (PackageAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{1}
}

// Committee represents a set of members authorized for stable-ramp operations.
type Committee struct {
	// members is the list of committee members.
	Members []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// threshold is the required signature ratio.
	Threshold *Threshold `protobuf:"bytes,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
}

func (m *Committee) Reset()         { *m = Committee{} }
func (m *Committee) String() string { return proto.CompactTextString(m) }
func (*Committee) ProtoMessage()    {}
func (*Committee) Descriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{0}
}
func (m *Committee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Committee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Committee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Committee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Committee.Merge(m, src)
}
func (m *Committee) XXX_Size() int {
	return m.Size()
}
func (m *Committee) XXX_DiscardUnknown() {
	xxx_messageInfo_Committee.DiscardUnknown(m)
}

var xxx_messageInfo_Committee proto.InternalMessageInfo

func (m *Committee) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Committee) GetThreshold() *Threshold {
	if m != nil {
		return m.Threshold
	}
	return nil
}

// Threshold represents a signature threshold as a numerator over a denominator.
type Threshold struct {
	// numerator is the required portion of the threshold ratio.
	Numerator uint32 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	// denominator is the total portion of the threshold ratio.
	Denominator uint32 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (m *Threshold) Reset()         { *m = Threshold{} }
func (m *Threshold) String() string { return proto.CompactTextString(m) }
func (*Threshold) ProtoMessage()    {}
func (*Threshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{1}
}
func (m *Threshold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Threshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Threshold.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Threshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Threshold.Merge(m, src)
}
func (m *Threshold) XXX_Size() int {
	return m.Size()
}
func (m *Threshold) XXX_DiscardUnknown() {
	xxx_messageInfo_Threshold.DiscardUnknown(m)
}

var xxx_messageInfo_Threshold proto.InternalMessageInfo

func (m *Threshold) GetNumerator() uint32 {
	if m != nil {
		return m.Numerator
	}
	return 0
}

func (m *Threshold) GetDenominator() uint32 {
	if m != nil {
		return m.Denominator
	}
	return 0
}

// Member represents a committee member's Realio and external-chain public keys.
type Member struct {
	// realio_pubkey is the member's native Realio hex-encoded public key.
	RealioPubkey string `protobuf:"bytes,1,opt,name=realio_pubkey,json=realioPubkey,proto3" json:"realio_pubkey,omitempty"`
	// external_pubkey is the member's hex-encoded public key for another chain's
	// signature scheme.
	ExternalPubkey string `protobuf:"bytes,2,opt,name=external_pubkey,json=externalPubkey,proto3" json:"external_pubkey,omitempty"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{2}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Member.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return m.Size()
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetRealioPubkey() string {
	if m != nil {
		return m.RealioPubkey
	}
	return ""
}

func (m *Member) GetExternalPubkey() string {
	if m != nil {
		return m.ExternalPubkey
	}
	return ""
}

// Package represents a stable-ramp transfer package.
type Package struct {
	// sender_addr is the sender address.
	SenderAddr string `protobuf:"bytes,1,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"`
	// receiver_addr is the receiver address.
	ReceiverAddr string `protobuf:"bytes,2,opt,name=receiver_addr,json=receiverAddr,proto3" json:"receiver_addr,omitempty"`
	// connection_id is the connection identifier.
	ConnectionId string `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// amount is the transfer amount.
	Amount uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// denom is the transfer denomination.
	Denom string `protobuf:"bytes,5,opt,name=denom,proto3" json:"denom,omitempty"`
	// nonce is the package nonce.
	Nonce uint64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// status is the package status.
	Status PackageStatus `protobuf:"varint,7,opt,name=status,proto3,enum=realionetwork.stable.v1.PackageStatus" json:"status,omitempty"`
	// action is the package action.
	Action PackageAction `protobuf:"varint,8,opt,name=action,proto3,enum=realionetwork.stable.v1.PackageAction" json:"action,omitempty"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{3}
}
func (m *Package) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Package.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return m.Size()
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetSenderAddr() string {
	if m != nil {
		return m.SenderAddr
	}
	return ""
}

func (m *Package) GetReceiverAddr() string {
	if m != nil {
		return m.ReceiverAddr
	}
	return ""
}

func (m *Package) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *Package) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Package) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Package) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Package) GetStatus() PackageStatus {
	if m != nil {
		return m.Status
	}
	return PackageStatus_PACKAGE_STATUS_UNSPECIFIED
}

func (m *Package) GetAction() PackageAction {
	if m != nil {
		return m.Action
	}
	return PackageAction_PACKAGE_ACTION_UNSPECIFIED
}

// TrackedPackage wraps a package with committee approval tracking.
type TrackedPackage struct {
	// package_data is the package being tracked.
	PackageData *Package `protobuf:"bytes,1,opt,name=package_data,json=packageData,proto3" json:"package_data,omitempty"`
	// approvals is the number of committee member approvals for the package.
	Approvals uint32 `protobuf:"varint,2,opt,name=approvals,proto3" json:"approvals,omitempty"`
	// total_members is the total number of committee members for the package.
	TotalMembers uint32 `protobuf:"varint,3,opt,name=total_members,json=totalMembers,proto3" json:"total_members,omitempty"`
	// signatures are member signatures collected for the package.
	Signatures [][]byte `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// voted_members tracks bech32 addresses of members who have already voted.
	VotedMembers []string `protobuf:"bytes,5,rep,name=voted_members,json=votedMembers,proto3" json:"voted_members,omitempty"`
}

func (m *TrackedPackage) Reset()         { *m = TrackedPackage{} }
func (m *TrackedPackage) String() string { return proto.CompactTextString(m) }
func (*TrackedPackage) ProtoMessage()    {}
func (*TrackedPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8248a3979cd46c60, []int{4}
}
func (m *TrackedPackage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrackedPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrackedPackage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrackedPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackedPackage.Merge(m, src)
}
func (m *TrackedPackage) XXX_Size() int {
	return m.Size()
}
func (m *TrackedPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackedPackage.DiscardUnknown(m)
}

var xxx_messageInfo_TrackedPackage proto.InternalMessageInfo

func (m *TrackedPackage) GetPackageData() *Package {
	if m != nil {
		return m.PackageData
	}
	return nil
}

func (m *TrackedPackage) GetApprovals() uint32 {
	if m != nil {
		return m.Approvals
	}
	return 0
}

func (m *TrackedPackage) GetTotalMembers() uint32 {
	if m != nil {
		return m.TotalMembers
	}
	return 0
}

func (m *TrackedPackage) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *TrackedPackage) GetVotedMembers() []string {
	if m != nil {
		return m.VotedMembers
	}
	return nil
}

func init() {
	proto.RegisterEnum("realionetwork.stable.v1.PackageStatus", PackageStatus_name, PackageStatus_value)
	proto.RegisterEnum("realionetwork.stable.v1.PackageAction", PackageAction_name, PackageAction_value)
	proto.RegisterType((*Committee)(nil), "realionetwork.stable.v1.Committee")
	proto.RegisterType((*Threshold)(nil), "realionetwork.stable.v1.Threshold")
	proto.RegisterType((*Member)(nil), "realionetwork.stable.v1.Member")
	proto.RegisterType((*Package)(nil), "realionetwork.stable.v1.Package")
	proto.RegisterType((*TrackedPackage)(nil), "realionetwork.stable.v1.TrackedPackage")
}

func init() {
	proto.RegisterFile("realionetwork/stable/v1/stable.proto", fileDescriptor_8248a3979cd46c60)
}

var fileDescriptor_8248a3979cd46c60 = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x4f, 0xdb, 0x48,
	0x18, 0x86, 0x33, 0x09, 0x84, 0xcd, 0x24, 0xb0, 0xd1, 0x68, 0x17, 0xbc, 0x2c, 0x32, 0x56, 0x5a,
	0xb5, 0x11, 0x12, 0x89, 0x48, 0x2f, 0xed, 0xa5, 0xaa, 0x1b, 0x1b, 0x6a, 0x01, 0xc1, 0x72, 0x4c,
	0x91, 0x7a, 0xb1, 0x26, 0xf6, 0x88, 0x58, 0x89, 0x3d, 0xd6, 0x78, 0x92, 0xc2, 0xbd, 0x87, 0x1e,
	0xfb, 0x73, 0xfa, 0x13, 0x7a, 0xe4, 0xd8, 0x4b, 0xa5, 0x0a, 0xfe, 0x48, 0x95, 0xf1, 0x98, 0x40,
	0xa4, 0xa8, 0xbd, 0xcd, 0xbc, 0xef, 0xf3, 0x7e, 0xfe, 0xfc, 0xcd, 0x68, 0xe0, 0x53, 0x46, 0xf0,
	0x38, 0xa4, 0x31, 0xe1, 0x1f, 0x29, 0x1b, 0xb5, 0x53, 0x8e, 0x07, 0x63, 0xd2, 0x9e, 0x1e, 0xc8,
	0x55, 0x2b, 0x61, 0x94, 0x53, 0xb4, 0xf5, 0x88, 0x6a, 0x49, 0x6f, 0x7a, 0xd0, 0xf8, 0x0c, 0x60,
	0xa5, 0x4b, 0xa3, 0x28, 0xe4, 0x9c, 0x10, 0xf4, 0x0a, 0xae, 0x45, 0x24, 0x1a, 0x10, 0x96, 0x2a,
	0x40, 0x2b, 0x35, 0xab, 0x9d, 0xdd, 0xd6, 0x92, 0x60, 0xeb, 0x54, 0x70, 0x4e, 0xce, 0xa3, 0x37,
	0xb0, 0xc2, 0x87, 0x8c, 0xa4, 0x43, 0x3a, 0x0e, 0x94, 0xa2, 0x06, 0x9a, 0xd5, 0x4e, 0x63, 0x69,
	0xd8, 0xcd, 0x49, 0x67, 0x1e, 0x6a, 0x1c, 0xc3, 0xca, 0xbd, 0x8e, 0x76, 0x60, 0x25, 0x9e, 0x44,
	0x84, 0x61, 0x4e, 0x99, 0x02, 0x34, 0xd0, 0x5c, 0x77, 0xe6, 0x02, 0xd2, 0x60, 0x35, 0x20, 0x31,
	0x8d, 0xc2, 0x58, 0xf8, 0x45, 0xe1, 0x3f, 0x94, 0x1a, 0xef, 0x61, 0x39, 0xeb, 0x10, 0x3d, 0x81,
	0xeb, 0x59, 0x1b, 0x5e, 0x32, 0x19, 0x8c, 0xc8, 0xb5, 0xa8, 0x56, 0x71, 0x6a, 0x99, 0x68, 0x0b,
	0x0d, 0x3d, 0x87, 0x7f, 0x93, 0x2b, 0x4e, 0x58, 0x8c, 0xc7, 0x39, 0x56, 0x14, 0xd8, 0x46, 0x2e,
	0x67, 0x60, 0xe3, 0x6b, 0x11, 0xae, 0xd9, 0xd8, 0x1f, 0xe1, 0x4b, 0x82, 0x76, 0x61, 0x35, 0x25,
	0x71, 0x40, 0x98, 0x87, 0x83, 0x80, 0xc9, 0xba, 0x30, 0x93, 0xf4, 0x20, 0x90, 0x9f, 0xf6, 0x49,
	0x38, 0xcd, 0x91, 0x62, 0xfe, 0xe9, 0x4c, 0xcc, 0x21, 0x9f, 0xc6, 0x31, 0xf1, 0x79, 0x48, 0x63,
	0x2f, 0x0c, 0x94, 0x52, 0x06, 0xcd, 0x45, 0x2b, 0x40, 0x9b, 0xb0, 0x8c, 0x23, 0x3a, 0x89, 0xb9,
	0xb2, 0xa2, 0x81, 0xe6, 0x8a, 0x23, 0x77, 0xe8, 0x1f, 0xb8, 0x2a, 0xfe, 0x5a, 0x59, 0x15, 0xa1,
	0x6c, 0x33, 0x53, 0x63, 0x1a, 0xfb, 0x44, 0x29, 0x0b, 0x38, 0xdb, 0xa0, 0xd7, 0xb0, 0x9c, 0x72,
	0xcc, 0x27, 0xa9, 0xb2, 0xa6, 0x81, 0xe6, 0x46, 0xe7, 0xd9, 0xd2, 0xe3, 0x91, 0x3f, 0xd8, 0x17,
	0xb4, 0x23, 0x53, 0xb3, 0x3c, 0x16, 0xfd, 0x28, 0x7f, 0xfd, 0x59, 0x5e, 0x17, 0xb4, 0x23, 0x53,
	0x8d, 0x1f, 0x00, 0x6e, 0xb8, 0x0c, 0xfb, 0x23, 0x12, 0xe4, 0x13, 0xec, 0xc2, 0x5a, 0x92, 0x2d,
	0xbd, 0x00, 0x73, 0x2c, 0x46, 0x58, 0xed, 0x68, 0xbf, 0x2b, 0xec, 0x54, 0x65, 0xca, 0xc0, 0x1c,
	0xcf, 0xae, 0x0a, 0x4e, 0x12, 0x46, 0xa7, 0x78, 0x9c, 0xca, 0xab, 0x30, 0x17, 0x66, 0xe3, 0xe5,
	0x94, 0xe3, 0xb1, 0x97, 0x5f, 0xec, 0x92, 0x20, 0x6a, 0x42, 0x3c, 0x95, 0x97, 0x57, 0x85, 0x30,
	0x0d, 0x2f, 0x63, 0xcc, 0x27, 0x8c, 0xa4, 0xca, 0x8a, 0x56, 0x6a, 0xd6, 0x9c, 0x07, 0xca, 0xac,
	0xc8, 0x94, 0x72, 0x12, 0xdc, 0x17, 0x59, 0xd5, 0x4a, 0xb3, 0x33, 0x12, 0xa2, 0x2c, 0xb2, 0xf7,
	0x09, 0xc0, 0xf5, 0x47, 0x93, 0x43, 0x2a, 0xdc, 0xb6, 0xf5, 0xee, 0xb1, 0x7e, 0x64, 0x7a, 0x7d,
	0x57, 0x77, 0xcf, 0xfb, 0xde, 0x79, 0xaf, 0x6f, 0x9b, 0x5d, 0xeb, 0xd0, 0x32, 0x8d, 0x7a, 0x01,
	0x6d, 0xc3, 0xcd, 0x05, 0xdf, 0x36, 0x7b, 0x86, 0xd5, 0x3b, 0xaa, 0x03, 0xb4, 0x03, 0x95, 0x05,
	0xaf, 0x7b, 0x76, 0x6a, 0x9f, 0x98, 0xae, 0x69, 0xd4, 0x8b, 0xe8, 0x3f, 0xf8, 0xef, 0x82, 0x7b,
	0xa8, 0x5b, 0x27, 0xa6, 0x51, 0x2f, 0xed, 0x0d, 0xef, 0xbb, 0xc8, 0xe6, 0xff, 0xb0, 0x0b, 0xbd,
	0xeb, 0x5a, 0x67, 0xbd, 0xe5, 0x5d, 0x48, 0xdf, 0x30, 0xed, 0xb3, 0xbe, 0xe5, 0xd6, 0x01, 0xfa,
	0x1f, 0x6e, 0x2d, 0x78, 0x17, 0x96, 0xfb, 0xce, 0x70, 0xf4, 0x8b, 0x7a, 0xf1, 0xad, 0xf3, 0xed,
	0x56, 0x05, 0x37, 0xb7, 0x2a, 0xf8, 0x79, 0xab, 0x82, 0x2f, 0x77, 0x6a, 0xe1, 0xe6, 0x4e, 0x2d,
	0x7c, 0xbf, 0x53, 0x0b, 0x1f, 0x5e, 0x5e, 0x86, 0x7c, 0x38, 0x19, 0xb4, 0x7c, 0x1a, 0xb5, 0xb3,
	0xb3, 0xe4, 0xc4, 0x1f, 0xca, 0xe5, 0x7e, 0xfe, 0x56, 0x5d, 0xc9, 0x37, 0x6a, 0x9f, 0xe1, 0x28,
	0x69, 0xf3, 0xeb, 0x84, 0xa4, 0x83, 0xb2, 0x78, 0xaf, 0x5e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0x6a, 0x29, 0x86, 0xd7, 0x04, 0x00, 0x00,
}

func (m *Committee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Committee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Committee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Threshold != nil {
		{
			size, err := m.Threshold.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStable(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Members) > 0 {
		for iNdEx := len(m.Members) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Members[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStable(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Threshold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Threshold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Threshold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Denominator != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Denominator))
		i--
		dAtA[i] = 0x10
	}
	if m.Numerator != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Numerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Member) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Member) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Member) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExternalPubkey) > 0 {
		i -= len(m.ExternalPubkey)
		copy(dAtA[i:], m.ExternalPubkey)
		i = encodeVarintStable(dAtA, i, uint64(len(m.ExternalPubkey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RealioPubkey) > 0 {
		i -= len(m.RealioPubkey)
		copy(dAtA[i:], m.RealioPubkey)
		i = encodeVarintStable(dAtA, i, uint64(len(m.RealioPubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Package) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Package) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Package) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Action != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x40
	}
	if m.Status != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.Nonce != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintStable(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Amount != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintStable(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ReceiverAddr) > 0 {
		i -= len(m.ReceiverAddr)
		copy(dAtA[i:], m.ReceiverAddr)
		i = encodeVarintStable(dAtA, i, uint64(len(m.ReceiverAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SenderAddr) > 0 {
		i -= len(m.SenderAddr)
		copy(dAtA[i:], m.SenderAddr)
		i = encodeVarintStable(dAtA, i, uint64(len(m.SenderAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrackedPackage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrackedPackage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrackedPackage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VotedMembers) > 0 {
		for iNdEx := len(m.VotedMembers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.VotedMembers[iNdEx])
			copy(dAtA[i:], m.VotedMembers[iNdEx])
			i = encodeVarintStable(dAtA, i, uint64(len(m.VotedMembers[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signatures[iNdEx])
			copy(dAtA[i:], m.Signatures[iNdEx])
			i = encodeVarintStable(dAtA, i, uint64(len(m.Signatures[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.TotalMembers != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.TotalMembers))
		i--
		dAtA[i] = 0x18
	}
	if m.Approvals != 0 {
		i = encodeVarintStable(dAtA, i, uint64(m.Approvals))
		i--
		dAtA[i] = 0x10
	}
	if m.PackageData != nil {
		{
			size, err := m.PackageData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStable(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStable(dAtA []byte, offset int, v uint64) int {
	offset -= sovStable(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Committee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Members) > 0 {
		for _, e := range m.Members {
			l = e.Size()
			n += 1 + l + sovStable(uint64(l))
		}
	}
	if m.Threshold != nil {
		l = m.Threshold.Size()
		n += 1 + l + sovStable(uint64(l))
	}
	return n
}

func (m *Threshold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Numerator != 0 {
		n += 1 + sovStable(uint64(m.Numerator))
	}
	if m.Denominator != 0 {
		n += 1 + sovStable(uint64(m.Denominator))
	}
	return n
}

func (m *Member) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RealioPubkey)
	if l > 0 {
		n += 1 + l + sovStable(uint64(l))
	}
	l = len(m.ExternalPubkey)
	if l > 0 {
		n += 1 + l + sovStable(uint64(l))
	}
	return n
}

func (m *Package) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SenderAddr)
	if l > 0 {
		n += 1 + l + sovStable(uint64(l))
	}
	l = len(m.ReceiverAddr)
	if l > 0 {
		n += 1 + l + sovStable(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovStable(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovStable(uint64(m.Amount))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovStable(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovStable(uint64(m.Nonce))
	}
	if m.Status != 0 {
		n += 1 + sovStable(uint64(m.Status))
	}
	if m.Action != 0 {
		n += 1 + sovStable(uint64(m.Action))
	}
	return n
}

func (m *TrackedPackage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PackageData != nil {
		l = m.PackageData.Size()
		n += 1 + l + sovStable(uint64(l))
	}
	if m.Approvals != 0 {
		n += 1 + sovStable(uint64(m.Approvals))
	}
	if m.TotalMembers != 0 {
		n += 1 + sovStable(uint64(m.TotalMembers))
	}
	if len(m.Signatures) > 0 {
		for _, b := range m.Signatures {
			l = len(b)
			n += 1 + l + sovStable(uint64(l))
		}
	}
	if len(m.VotedMembers) > 0 {
		for _, s := range m.VotedMembers {
			l = len(s)
			n += 1 + l + sovStable(uint64(l))
		}
	}
	return n
}

func sovStable(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStable(x uint64) (n int) {
	return sovStable(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Committee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStable
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Committee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Committee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Members", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Members = append(m.Members, &Member{})
			if err := m.Members[len(m.Members)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Threshold == nil {
				m.Threshold = &Threshold{}
			}
			if err := m.Threshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStable(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStable
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Threshold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStable
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Threshold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Threshold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Numerator", wireType)
			}
			m.Numerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Numerator |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denominator", wireType)
			}
			m.Denominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Denominator |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStable(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStable
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Member) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStable
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Member: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Member: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealioPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RealioPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExternalPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStable(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStable
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Package) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStable
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Package: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Package: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PackageStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= PackageAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStable(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStable
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrackedPackage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStable
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrackedPackage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrackedPackage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PackageData == nil {
				m.PackageData = &Package{}
			}
			if err := m.PackageData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			m.Approvals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Approvals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMembers", wireType)
			}
			m.TotalMembers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalMembers |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, make([]byte, postIndex-iNdEx))
			copy(m.Signatures[len(m.Signatures)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotedMembers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStable
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStable
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStable
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VotedMembers = append(m.VotedMembers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStable(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStable
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStable(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStable
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStable
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStable
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStable
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStable
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStable
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStable        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStable          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStable = fmt.Errorf("proto: unexpected end of group")
)
