// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: realionetwork/stable/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClaimAction represents a committee member's package claim action.
type ClaimAction int32

const (
	// CLAIM_ACTION_UNSPECIFIED defines an unknown claim action.
	ClaimAction_CLAIM_ACTION_UNSPECIFIED ClaimAction = 0
	// CLAIM_ACTION_APPROVE defines an approval claim action.
	ClaimAction_CLAIM_ACTION_APPROVE ClaimAction = 1
	// CLAIM_ACTION_REJECT defines a rejection claim action.
	ClaimAction_CLAIM_ACTION_REJECT ClaimAction = 2
)

var ClaimAction_name = map[int32]string{
	0: "CLAIM_ACTION_UNSPECIFIED",
	1: "CLAIM_ACTION_APPROVE",
	2: "CLAIM_ACTION_REJECT",
}

var ClaimAction_value = map[string]int32{
	"CLAIM_ACTION_UNSPECIFIED": 0,
	"CLAIM_ACTION_APPROVE":     1,
	"CLAIM_ACTION_REJECT":      2,
}

func (x ClaimAction) String() string {
	return proto.EnumName(ClaimAction_name, int32(x))
}

func (ClaimAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{0}
}

// MsgWithdraw defines a request to withdraw stable-ramp funds.
type MsgWithdraw struct {
	// sender_addr is the signer address initiating the withdraw.
	SenderAddr string `protobuf:"bytes,1,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"`
	// receiver_addr is the destination Ethereum address.
	ReceiverAddr string `protobuf:"bytes,2,opt,name=receiver_addr,json=receiverAddr,proto3" json:"receiver_addr,omitempty"`
	// amount is the withdrawal amount.
	Amount uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// connection_id is the connection identifier.
	ConnectionId string `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// token_address is the ERC20 contract address of the token being withdrawn.
	TokenAddress string `protobuf:"bytes,5,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
}

func (m *MsgWithdraw) Reset()         { *m = MsgWithdraw{} }
func (m *MsgWithdraw) String() string { return proto.CompactTextString(m) }
func (*MsgWithdraw) ProtoMessage()    {}
func (*MsgWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{0}
}
func (m *MsgWithdraw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdraw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdraw.Merge(m, src)
}
func (m *MsgWithdraw) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdraw proto.InternalMessageInfo

func (m *MsgWithdraw) GetSenderAddr() string {
	if m != nil {
		return m.SenderAddr
	}
	return ""
}

func (m *MsgWithdraw) GetReceiverAddr() string {
	if m != nil {
		return m.ReceiverAddr
	}
	return ""
}

func (m *MsgWithdraw) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgWithdraw) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *MsgWithdraw) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

// MsgWithdrawResponse defines the response for a withdraw request.
type MsgWithdrawResponse struct {
}

func (m *MsgWithdrawResponse) Reset()         { *m = MsgWithdrawResponse{} }
func (m *MsgWithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawResponse) ProtoMessage()    {}
func (*MsgWithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{1}
}
func (m *MsgWithdrawResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawResponse.Merge(m, src)
}
func (m *MsgWithdrawResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawResponse proto.InternalMessageInfo

// MsgDepositClaim defines a request to approve or reject a deposit package.
type MsgDepositClaim struct {
	// member_addr is the committee member signer address.
	MemberAddr string `protobuf:"bytes,1,opt,name=member_addr,json=memberAddr,proto3" json:"member_addr,omitempty"`
	// package_nonce is the nonce of the package being claimed.
	PackageNonce uint64 `protobuf:"varint,2,opt,name=package_nonce,json=packageNonce,proto3" json:"package_nonce,omitempty"`
	// action is the member's claim action.
	Action ClaimAction `protobuf:"varint,3,opt,name=action,proto3,enum=realionetwork.stable.v1.ClaimAction" json:"action,omitempty"`
	// connection_id is the connection identifier.
	ConnectionId string `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
}

func (m *MsgDepositClaim) Reset()         { *m = MsgDepositClaim{} }
func (m *MsgDepositClaim) String() string { return proto.CompactTextString(m) }
func (*MsgDepositClaim) ProtoMessage()    {}
func (*MsgDepositClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{2}
}
func (m *MsgDepositClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositClaim.Merge(m, src)
}
func (m *MsgDepositClaim) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositClaim proto.InternalMessageInfo

func (m *MsgDepositClaim) GetMemberAddr() string {
	if m != nil {
		return m.MemberAddr
	}
	return ""
}

func (m *MsgDepositClaim) GetPackageNonce() uint64 {
	if m != nil {
		return m.PackageNonce
	}
	return 0
}

func (m *MsgDepositClaim) GetAction() ClaimAction {
	if m != nil {
		return m.Action
	}
	return ClaimAction_CLAIM_ACTION_UNSPECIFIED
}

func (m *MsgDepositClaim) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// MsgDepositClaimResponse defines the response for a deposit claim request.
type MsgDepositClaimResponse struct {
}

func (m *MsgDepositClaimResponse) Reset()         { *m = MsgDepositClaimResponse{} }
func (m *MsgDepositClaimResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositClaimResponse) ProtoMessage()    {}
func (*MsgDepositClaimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{3}
}
func (m *MsgDepositClaimResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositClaimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositClaimResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositClaimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositClaimResponse.Merge(m, src)
}
func (m *MsgDepositClaimResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositClaimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositClaimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositClaimResponse proto.InternalMessageInfo

// MsgWithdrawClaim defines a request to approve or reject a withdrawal package.
type MsgWithdrawClaim struct {
	// member_addr is the committee member signer address.
	MemberAddr string `protobuf:"bytes,1,opt,name=member_addr,json=memberAddr,proto3" json:"member_addr,omitempty"`
	// package_nonce is the nonce of the package being claimed.
	PackageNonce uint64 `protobuf:"varint,2,opt,name=package_nonce,json=packageNonce,proto3" json:"package_nonce,omitempty"`
	// action is the member's claim action.
	Action ClaimAction `protobuf:"varint,3,opt,name=action,proto3,enum=realionetwork.stable.v1.ClaimAction" json:"action,omitempty"`
	// signature is the member signature for the withdrawal package.
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// connection_id is the connection identifier.
	ConnectionId string `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
}

func (m *MsgWithdrawClaim) Reset()         { *m = MsgWithdrawClaim{} }
func (m *MsgWithdrawClaim) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawClaim) ProtoMessage()    {}
func (*MsgWithdrawClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{4}
}
func (m *MsgWithdrawClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawClaim.Merge(m, src)
}
func (m *MsgWithdrawClaim) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawClaim proto.InternalMessageInfo

func (m *MsgWithdrawClaim) GetMemberAddr() string {
	if m != nil {
		return m.MemberAddr
	}
	return ""
}

func (m *MsgWithdrawClaim) GetPackageNonce() uint64 {
	if m != nil {
		return m.PackageNonce
	}
	return 0
}

func (m *MsgWithdrawClaim) GetAction() ClaimAction {
	if m != nil {
		return m.Action
	}
	return ClaimAction_CLAIM_ACTION_UNSPECIFIED
}

func (m *MsgWithdrawClaim) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *MsgWithdrawClaim) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// MsgWithdrawClaimResponse defines the response for a withdrawal claim request.
type MsgWithdrawClaimResponse struct {
}

func (m *MsgWithdrawClaimResponse) Reset()         { *m = MsgWithdrawClaimResponse{} }
func (m *MsgWithdrawClaimResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawClaimResponse) ProtoMessage()    {}
func (*MsgWithdrawClaimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_429bbb5166890ca7, []int{5}
}
func (m *MsgWithdrawClaimResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawClaimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawClaimResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawClaimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawClaimResponse.Merge(m, src)
}
func (m *MsgWithdrawClaimResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawClaimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawClaimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawClaimResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("realionetwork.stable.v1.ClaimAction", ClaimAction_name, ClaimAction_value)
	proto.RegisterType((*MsgWithdraw)(nil), "realionetwork.stable.v1.MsgWithdraw")
	proto.RegisterType((*MsgWithdrawResponse)(nil), "realionetwork.stable.v1.MsgWithdrawResponse")
	proto.RegisterType((*MsgDepositClaim)(nil), "realionetwork.stable.v1.MsgDepositClaim")
	proto.RegisterType((*MsgDepositClaimResponse)(nil), "realionetwork.stable.v1.MsgDepositClaimResponse")
	proto.RegisterType((*MsgWithdrawClaim)(nil), "realionetwork.stable.v1.MsgWithdrawClaim")
	proto.RegisterType((*MsgWithdrawClaimResponse)(nil), "realionetwork.stable.v1.MsgWithdrawClaimResponse")
}

func init() { proto.RegisterFile("realionetwork/stable/v1/tx.proto", fileDescriptor_429bbb5166890ca7) }

var fileDescriptor_429bbb5166890ca7 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xc1, 0x8e, 0xd2, 0x40,
	0x18, 0xc7, 0x99, 0x5d, 0x20, 0xee, 0xc0, 0x2a, 0xe9, 0xaa, 0x54, 0xb2, 0xa9, 0x04, 0x3d, 0x20,
	0x71, 0x5b, 0x59, 0x2f, 0xc6, 0x78, 0xa9, 0x2c, 0x26, 0x18, 0x61, 0x49, 0x5d, 0x35, 0xf1, 0xb0,
	0x64, 0x68, 0x27, 0xa5, 0x42, 0x67, 0x9a, 0xce, 0xc0, 0xae, 0x37, 0xe3, 0x13, 0xf8, 0x28, 0xfb,
	0x16, 0xeb, 0xc1, 0xc3, 0x1e, 0x3d, 0x1a, 0x38, 0xec, 0xc1, 0x97, 0x30, 0x4c, 0x5b, 0xb6, 0xc5,
	0xac, 0xe9, 0xd1, 0x1b, 0xfc, 0xe7, 0xff, 0xcd, 0xf7, 0xfd, 0xfe, 0x99, 0x7e, 0xb0, 0xea, 0x63,
	0x34, 0x71, 0x28, 0xc1, 0xfc, 0x84, 0xfa, 0x63, 0x8d, 0x71, 0x34, 0x9c, 0x60, 0x6d, 0xd6, 0xd4,
	0xf8, 0xa9, 0xea, 0xf9, 0x94, 0x53, 0xa9, 0x9c, 0x70, 0xa8, 0x81, 0x43, 0x9d, 0x35, 0x2b, 0x65,
	0x93, 0x32, 0x97, 0x32, 0xcd, 0x65, 0xf6, 0xb2, 0xc0, 0x65, 0x76, 0x50, 0x51, 0x3b, 0x07, 0xb0,
	0xd0, 0x65, 0xf6, 0x07, 0x87, 0x8f, 0x2c, 0x1f, 0x9d, 0x48, 0xf7, 0x61, 0x81, 0x61, 0x62, 0x61,
	0x7f, 0x80, 0x2c, 0xcb, 0x97, 0x41, 0x15, 0xd4, 0xb7, 0x0c, 0x18, 0x48, 0xba, 0x65, 0xf9, 0xd2,
	0x03, 0xb8, 0xed, 0x63, 0x13, 0x3b, 0xb3, 0xc8, 0xb2, 0x21, 0x2c, 0xc5, 0x48, 0x14, 0xa6, 0xbb,
	0x30, 0x8f, 0x5c, 0x3a, 0x25, 0x5c, 0xde, 0xac, 0x82, 0x7a, 0xd6, 0x08, 0xff, 0x2d, 0x8b, 0x4d,
	0x4a, 0x08, 0x36, 0xb9, 0x43, 0xc9, 0xc0, 0xb1, 0xe4, 0x6c, 0x50, 0x7c, 0x25, 0x76, 0xac, 0xa5,
	0x89, 0xd3, 0x31, 0x26, 0xe2, 0x7a, 0xcc, 0x98, 0x9c, 0x0b, 0x4c, 0x42, 0xd4, 0x03, 0xed, 0x79,
	0xe9, 0xeb, 0xe5, 0x59, 0x23, 0x3e, 0x6a, 0xed, 0x0e, 0xdc, 0x89, 0x81, 0x18, 0x98, 0x79, 0x94,
	0x30, 0x5c, 0xfb, 0x01, 0xe0, 0xad, 0x2e, 0xb3, 0x0f, 0xb0, 0x47, 0x99, 0xc3, 0x5b, 0x13, 0xe4,
	0xb8, 0x4b, 0x48, 0x17, 0xbb, 0xc3, 0x35, 0xc8, 0x40, 0x8a, 0x20, 0x3d, 0x64, 0x8e, 0x91, 0x8d,
	0x07, 0x84, 0x12, 0x13, 0x0b, 0xc8, 0xac, 0x51, 0x0c, 0xc5, 0xde, 0x52, 0x93, 0x5e, 0xc0, 0x3c,
	0x12, 0x33, 0x0b, 0xc8, 0x9b, 0xfb, 0x0f, 0xd5, 0x6b, 0xd2, 0x57, 0x45, 0x57, 0x5d, 0x78, 0x8d,
	0xb0, 0x26, 0x55, 0x14, 0x21, 0x65, 0x6c, 0xd6, 0xda, 0x3d, 0x58, 0x5e, 0xa3, 0x59, 0x91, 0xfe,
	0x06, 0xb0, 0x14, 0x4b, 0xe0, 0xff, 0x41, 0xdd, 0x85, 0x5b, 0xcc, 0xb1, 0x09, 0xe2, 0x53, 0x1f,
	0x0b, 0xcc, 0xa2, 0x71, 0x25, 0xfc, 0x1d, 0x44, 0x2e, 0x55, 0x10, 0x15, 0x28, 0xaf, 0xc3, 0x46,
	0x49, 0x34, 0x8e, 0x61, 0x21, 0x36, 0x87, 0xb4, 0x0b, 0xe5, 0xd6, 0x1b, 0xbd, 0xd3, 0x1d, 0xe8,
	0xad, 0xa3, 0xce, 0x61, 0x6f, 0xf0, 0xae, 0xf7, 0xb6, 0xdf, 0x6e, 0x75, 0x5e, 0x75, 0xda, 0x07,
	0xa5, 0x8c, 0x24, 0xc3, 0xdb, 0x89, 0x53, 0xbd, 0xdf, 0x37, 0x0e, 0xdf, 0xb7, 0x4b, 0x40, 0x2a,
	0xc3, 0x9d, 0xc4, 0x89, 0xd1, 0x7e, 0xdd, 0x6e, 0x1d, 0x95, 0x36, 0xf6, 0xcf, 0x37, 0xe0, 0x66,
	0x97, 0xd9, 0xd2, 0x31, 0xbc, 0xb1, 0xfa, 0x70, 0xae, 0x8f, 0x24, 0x36, 0x66, 0xe5, 0x71, 0x1a,
	0x57, 0xc4, 0x21, 0x7d, 0x82, 0xc5, 0xc4, 0xbb, 0xad, 0xff, 0xab, 0x3a, 0xee, 0xac, 0x3c, 0x49,
	0xeb, 0x5c, 0xf5, 0x72, 0xe1, 0x76, 0xf2, 0xe5, 0x3c, 0x4a, 0x33, 0x6a, 0xd0, 0xad, 0x99, 0xda,
	0x1a, 0xb5, 0xab, 0xe4, 0xbe, 0x5c, 0x9e, 0x35, 0xc0, 0x4b, 0xe3, 0xfb, 0x5c, 0x01, 0x17, 0x73,
	0x05, 0xfc, 0x9a, 0x2b, 0xe0, 0xdb, 0x42, 0xc9, 0x5c, 0x2c, 0x94, 0xcc, 0xcf, 0x85, 0x92, 0xf9,
	0xf8, 0xcc, 0x76, 0xf8, 0x68, 0x3a, 0x54, 0x4d, 0xea, 0x6a, 0xc1, 0xed, 0x1c, 0x9b, 0xa3, 0xf0,
	0xe7, 0x5e, 0xb4, 0x03, 0x4f, 0xc3, 0x2d, 0xb8, 0xe7, 0x23, 0xd7, 0xd3, 0xf8, 0x67, 0x0f, 0xb3,
	0x61, 0x5e, 0x6c, 0xb6, 0xa7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x3f, 0xfa, 0xd6, 0x2f,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Withdraw defines a method for withdrawing stable-ramp funds.
	Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error)
	// DepositClaim defines a method for claiming a deposit package.
	DepositClaim(ctx context.Context, in *MsgDepositClaim, opts ...grpc.CallOption) (*MsgDepositClaimResponse, error)
	// WithdrawClaim defines a method for claiming a withdrawal package.
	WithdrawClaim(ctx context.Context, in *MsgWithdrawClaim, opts ...grpc.CallOption) (*MsgWithdrawClaimResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error) {
	out := new(MsgWithdrawResponse)
	err := c.cc.Invoke(ctx, "/realionetwork.stable.v1.Msg/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DepositClaim(ctx context.Context, in *MsgDepositClaim, opts ...grpc.CallOption) (*MsgDepositClaimResponse, error) {
	out := new(MsgDepositClaimResponse)
	err := c.cc.Invoke(ctx, "/realionetwork.stable.v1.Msg/DepositClaim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawClaim(ctx context.Context, in *MsgWithdrawClaim, opts ...grpc.CallOption) (*MsgWithdrawClaimResponse, error) {
	out := new(MsgWithdrawClaimResponse)
	err := c.cc.Invoke(ctx, "/realionetwork.stable.v1.Msg/WithdrawClaim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Withdraw defines a method for withdrawing stable-ramp funds.
	Withdraw(context.Context, *MsgWithdraw) (*MsgWithdrawResponse, error)
	// DepositClaim defines a method for claiming a deposit package.
	DepositClaim(context.Context, *MsgDepositClaim) (*MsgDepositClaimResponse, error)
	// WithdrawClaim defines a method for claiming a withdrawal package.
	WithdrawClaim(context.Context, *MsgWithdrawClaim) (*MsgWithdrawClaimResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Withdraw(ctx context.Context, req *MsgWithdraw) (*MsgWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedMsgServer) DepositClaim(ctx context.Context, req *MsgDepositClaim) (*MsgDepositClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositClaim not implemented")
}
func (*UnimplementedMsgServer) WithdrawClaim(ctx context.Context, req *MsgWithdrawClaim) (*MsgWithdrawClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawClaim not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdraw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/realionetwork.stable.v1.Msg/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Withdraw(ctx, req.(*MsgWithdraw))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DepositClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositClaim)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DepositClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/realionetwork.stable.v1.Msg/DepositClaim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DepositClaim(ctx, req.(*MsgDepositClaim))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawClaim)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/realionetwork.stable.v1.Msg/WithdrawClaim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawClaim(ctx, req.(*MsgWithdrawClaim))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "realionetwork.stable.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Withdraw",
			Handler:    _Msg_Withdraw_Handler,
		},
		{
			MethodName: "DepositClaim",
			Handler:    _Msg_DepositClaim_Handler,
		},
		{
			MethodName: "WithdrawClaim",
			Handler:    _Msg_WithdrawClaim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "realionetwork/stable/v1/tx.proto",
}

func (m *MsgWithdraw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdraw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdraw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TokenAddress) > 0 {
		i -= len(m.TokenAddress)
		copy(dAtA[i:], m.TokenAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TokenAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ReceiverAddr) > 0 {
		i -= len(m.ReceiverAddr)
		copy(dAtA[i:], m.ReceiverAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReceiverAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SenderAddr) > 0 {
		i -= len(m.SenderAddr)
		copy(dAtA[i:], m.SenderAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SenderAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDepositClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x22
	}
	if m.Action != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x18
	}
	if m.PackageNonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PackageNonce))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MemberAddr) > 0 {
		i -= len(m.MemberAddr)
		copy(dAtA[i:], m.MemberAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MemberAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositClaimResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositClaimResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositClaimResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	if m.Action != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x18
	}
	if m.PackageNonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PackageNonce))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MemberAddr) > 0 {
		i -= len(m.MemberAddr)
		copy(dAtA[i:], m.MemberAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MemberAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawClaimResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawClaimResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawClaimResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgWithdraw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SenderAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ReceiverAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TokenAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDepositClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemberAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PackageNonce != 0 {
		n += 1 + sovTx(uint64(m.PackageNonce))
	}
	if m.Action != 0 {
		n += 1 + sovTx(uint64(m.Action))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDepositClaimResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemberAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PackageNonce != 0 {
		n += 1 + sovTx(uint64(m.PackageNonce))
	}
	if m.Action != 0 {
		n += 1 + sovTx(uint64(m.Action))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawClaimResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgWithdraw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdraw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdraw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageNonce", wireType)
			}
			m.PackageNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PackageNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= ClaimAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositClaimResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositClaimResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositClaimResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageNonce", wireType)
			}
			m.PackageNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PackageNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= ClaimAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawClaimResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawClaimResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawClaimResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
